import prisma from '@/lib/prisma';
import StrategyMap from '@/components/StrategyMap';
import { notFound } from 'next/navigation';
import { StartupPlan } from '@/lib/types';
import Link from 'next/link';

interface PublicProjectPageProps {
  params: Promise<{
    publicId: string;
  }>;
}

export default async function PublicProjectPage({ params }: PublicProjectPageProps) {
  const { publicId } = await params;

  const project = await prisma.project.findUnique({
    where: {
      publicId: publicId,
    },
    include: {
      strategyMaps: {
        orderBy: {
            createdAt: 'desc'
        },
        take: 1
      },
    },
  });

  if (!project) {
    notFound();
  }

  // Cast Json to StartupPlan
  const plan = project.strategyMaps?.[0]?.data as unknown as StartupPlan;

  return (
    <main className="min-h-screen bg-slate-50 dark:bg-slate-950 py-12 px-4 md:px-8">
      <div className="max-w-6xl mx-auto space-y-8">
        <header className="flex flex-col items-center space-y-2 mb-8 border-b pb-6">
           <h1 className="text-3xl font-bold tracking-tight text-slate-900 dark:text-slate-100 text-center">
             {project.title}
           </h1>
           <p className="text-slate-500 max-w-2xl text-center">
             {project.description}
           </p>
           <p className="text-xs text-slate-400 mt-2">
             Generated by <Link href="/" className="underline hover:text-slate-600">Startup Execution Platform</Link>
           </p>
        </header>

        {plan ? (
            <section>
                <StrategyMap plan={plan} />
            </section>
        ) : (
             <div className="text-center p-8 text-slate-500">
                Strategy map data unavailable.
             </div>
        )}
      </div>
    </main>
  );
}
